services:
  app:
    build: .
    container_name: ua-taxes-tg-bot
    env_file: .env
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
